# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 71217a4c5e5cb345d8910ee7bbdfa220bd6ca697c898980a03c38bcb13aea68381789e6ae005c56cdc0857fdfe6ab43cf71d18ae9051eb08a69df9a349e22a20

test:
  secret_key_base: a03a7c8243c905799ffb3c77d35c9400207919469283d45605576516b3b1551eefc94e4accd4a74bbb1544e034c27568c90a69278b0e1f810250067fae9a6820

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
